from django.db import models
from django.urls import reverse

# class MyTable(models.Model):
#     field1 = models.CharField(max_length=100)
#     field2 = models.IntegerField()
#     field3 = models.DateField(auto_now_add=True)



class CountryTable(models.Model):
    Rank = models.IntegerField()
    Name = models.CharField()
    Total_with_rent_1p = models.FloatField(default=0)
    Total_with_rent_3p = models.FloatField(default=0)
    _Without_rent_1p = models.FloatField(default=0)
    _Without_rent_3p = models.FloatField(default=0)
    Rent_and_Utilities_1p = models.FloatField(default=0)
    Rent_and_Utilities_3p = models.FloatField(default=0)
    _Food_1p = models.FloatField(default=0)
    _Food_3p = models.FloatField(default=0)
    Transport_1p = models.FloatField(default=0)
    Transport_3p = models.FloatField(default=0)
    Monthly_salary_after_tax = models.FloatField(default=0)
    Lunch_Menu = models.FloatField(default=0)
    Dinner_in_a_Restaurant = models.FloatField(default=0)
    Fast_food_meal = models.FloatField(default=0)
    Beer_in_a_Pub = models.FloatField(default=0)
    Cappuccino = models.FloatField(default=0)
    Pepsi_Coke = models.FloatField(default=0)
    _bedroom_apartment_in_city_Center = models.FloatField(default=0)
    Cheap_bedroom_apartment = models.FloatField(default=0)
    Utility_Bill_one_person = models.FloatField(default=0)
    Utility_Bill_for_a_Family = models.FloatField(default=0)
    Internet_plan = models.FloatField(default=0)
    Mortgage_Interest_Rate_for_Years = models.FloatField(default=0)
    _Apartment_price_to_Buy_in_city_Center = models.FloatField(default=0)
    House_price_to_Buy_in_Suburbs = models.FloatField(default=0)
    Local_transport_ticket = models.FloatField(default=0)
    _Monthly_ticket_local_transport = models.FloatField(default=0)
    Taxi_Ride = models.FloatField(default=0)
    Gas_Petrol = models.FloatField(default=0)
    Milk = models.FloatField(default=0)
    Bread = models.FloatField(default=0)
    Rice = models.FloatField(default=0)
    Eggs = models.FloatField(default=0)
    Cheese = models.FloatField(default=0)
    Chicken_Breast = models.FloatField(default=0)
    Round_Steak = models.FloatField(default=0)
    Apples = models.FloatField(default=0)
    Banana = models.FloatField(default=0)
    Oranges = models.FloatField(default=0)
    Tomato = models.FloatField(default=0)
    Potato = models.FloatField(default=0)
    Onion = models.FloatField(default=0)
    Water = models.FloatField(default=0)
    Coca_Cola_Pepsi = models.FloatField(default=0)
    Wine_mid_price = models.FloatField(default=0)
    Beer = models.FloatField(default=0)
    Cigarette_pack = models.FloatField(default=0)
    Cold_medicince = models.FloatField(default=0)
    Hair_Shampoo = models.FloatField(default=0)
    Toilet_paper = models.FloatField(default=0)
    Toothpaste = models.FloatField(default=0)
    _Gym_Membership = models.FloatField(default=0)
    Cinema_Ticket = models.FloatField(default=0)
    Doctors_visit = models.FloatField(default=0)
    Haircut = models.FloatField(default=0)
    Brand_Jeans = models.FloatField(default=0)
    Brand_Sneakers = models.FloatField(default=0)
    Daycare_or_Preschool = models.FloatField(default=0)
    International_Primary_School = models.FloatField(default=0)
    GDP_per_capita = models.IntegerField(default=0)
    Human_freedom_index = models.FloatField(default=0)
    _Life_expectancy = models.FloatField(default=0)
    English_speaking = models.FloatField(default=0)
    _Population = models.CharField(default='-')
    country_icon_url = models.CharField(default='-')
    country_flag_url = models.CharField(default='-')
    Quality_of_life = models.FloatField(default=0)


    def get_absolute_url(self):
        return reverse('cost', args=[self.Name])






class CityTable(models.Model):
    Name = models.CharField()
    country_name = models.CharField(default='-')
    Total_with_rent_1p = models.FloatField(default=0)
    Total_with_rent_3p = models.FloatField(default=0)
    _Without_rent_1p = models.FloatField(default=0)
    _Without_rent_3p = models.FloatField(default=0)
    Rent_and_Utilities_1p = models.FloatField(default=0)
    Rent_and_Utilities_3p = models.FloatField(default=0)
    _Food_1p = models.FloatField(default=0)
    _Food_3p = models.FloatField(default=0)
    Transport_1p = models.FloatField(default=0)
    Transport_3p = models.FloatField(default=0)
    Monthly_salary_after_tax = models.FloatField(default=0)
    Lunch_Menu = models.FloatField(default=0)
    Dinner_in_a_Restaurant = models.FloatField(default=0)
    Fast_food_meal = models.FloatField(default=0)
    Beer_in_a_Pub = models.FloatField(default=0)
    Cappuccino = models.FloatField(default=0)
    Pepsi_Coke = models.FloatField(default=0)
    _bedroom_apartment_in_city_Center = models.FloatField(default=0)
    Cheap_bedroom_apartment = models.FloatField(default=0)
    Utility_Bill_one_person = models.FloatField(default=0)
    Utility_Bill_for_a_Family = models.FloatField(default=0)
    Internet_plan = models.FloatField(default=0)
    Mortgage_Interest_Rate_for_Years = models.FloatField(default=0)
    _Apartment_price_to_Buy_in_city_Center = models.FloatField(default=0)
    House_price_to_Buy_in_Suburbs = models.FloatField(default=0)
    Local_transport_ticket = models.FloatField(default=0)
    _Monthly_ticket_local_transport = models.FloatField(default=0)
    Taxi_Ride = models.FloatField(default=0)
    Gas_Petrol = models.FloatField(default=0)
    Milk = models.FloatField(default=0)
    Bread = models.FloatField(default=0)
    Rice = models.FloatField(default=0)
    Eggs = models.FloatField(default=0)
    Cheese = models.FloatField(default=0)
    Chicken_Breast = models.FloatField(default=0)
    Round_Steak = models.FloatField(default=0)
    Apples = models.FloatField(default=0)
    Banana = models.FloatField(default=0)
    Oranges = models.FloatField(default=0)
    Tomato = models.FloatField(default=0)
    Potato = models.FloatField(default=0)
    Onion = models.FloatField(default=0)
    Water = models.FloatField(default=0)
    Coca_Cola_Pepsi = models.FloatField(default=0)
    Wine_mid_price = models.FloatField(default=0)
    Beer = models.FloatField(default=0)
    Cigarette_pack = models.FloatField(default=0)
    Cold_medicince = models.FloatField(default=0)
    Hair_Shampoo = models.FloatField(default=0)
    Toilet_paper = models.FloatField(default=0)
    Toothpaste = models.FloatField(default=0)
    _Gym_Membership = models.FloatField(default=0)
    Cinema_Ticket = models.FloatField(default=0)
    Doctors_visit = models.FloatField(default=0)
    Haircut = models.FloatField(default=0)
    Brand_Jeans = models.FloatField(default=0)
    Brand_Sneakers = models.FloatField(default=0)
    Daycare_or_Preschool = models.FloatField(default=0)
    International_Primary_School = models.FloatField(default=0)
    Quality_of_life = models.FloatField(default=0)
    _Population = models.CharField(default='-')
    country_icon_url = models.CharField(default='-')
    country_flag_url = models.CharField(default='-')
    Closest_airport = models.CharField(default='-')
    Closest_airport_val = models.CharField(default='no airport')
    Air_quality = models.CharField(default='-')
    Air_quality_val = models.CharField(default='-')
    Best_university_rank = models.CharField(default='-')
    Best_university_rank_val = models.CharField(default='-')
    state_name = models.CharField(default='-')
    Liveability = models.FloatField(default=0)

    def get_absolute_url(self):
        return reverse('city_cost', args=[self.country_name,self.Name])
    





class StateTable(models.Model):
    Name = models.CharField()
    country_name = models.CharField(default='-')
    Total_with_rent_1p = models.FloatField(default=0)
    Total_with_rent_3p = models.FloatField(default=0)
    _Without_rent_1p = models.FloatField(default=0)
    _Without_rent_3p = models.FloatField(default=0)
    Rent_and_Utilities_1p = models.FloatField(default=0)
    Rent_and_Utilities_3p = models.FloatField(default=0)
    _Food_1p = models.FloatField(default=0)
    _Food_3p = models.FloatField(default=0)
    Transport_1p = models.FloatField(default=0)
    Transport_3p = models.FloatField(default=0)
    Monthly_salary_after_tax = models.FloatField(default=0)
    Lunch_Menu = models.FloatField(default=0)
    Dinner_in_a_Restaurant = models.FloatField(default=0)
    Fast_food_meal = models.FloatField(default=0)
    Beer_in_a_Pub = models.FloatField(default=0)
    Cappuccino = models.FloatField(default=0)
    Pepsi_Coke = models.FloatField(default=0)
    _bedroom_apartment_in_city_Center = models.FloatField(default=0)
    Cheap_bedroom_apartment = models.FloatField(default=0)
    Utility_Bill_one_person = models.FloatField(default=0)
    Utility_Bill_for_a_Family = models.FloatField(default=0)
    Internet_plan = models.FloatField(default=0)
    Mortgage_Interest_Rate_for_Years = models.FloatField(default=0)
    _Apartment_price_to_Buy_in_city_Center = models.FloatField(default=0)
    House_price_to_Buy_in_Suburbs = models.FloatField(default=0)
    Local_transport_ticket = models.FloatField(default=0)
    _Monthly_ticket_local_transport = models.FloatField(default=0)
    Taxi_Ride = models.FloatField(default=0)
    Gas_Petrol = models.FloatField(default=0)
    Milk = models.FloatField(default=0)
    Bread = models.FloatField(default=0)
    Rice = models.FloatField(default=0)
    Eggs = models.FloatField(default=0)
    Cheese = models.FloatField(default=0)
    Chicken_Breast = models.FloatField(default=0)
    Round_Steak = models.FloatField(default=0)
    Apples = models.FloatField(default=0)
    Banana = models.FloatField(default=0)
    Oranges = models.FloatField(default=0)
    Tomato = models.FloatField(default=0)
    Potato = models.FloatField(default=0)
    Onion = models.FloatField(default=0)
    Water = models.FloatField(default=0)
    Coca_Cola_Pepsi = models.FloatField(default=0)
    Wine_mid_price = models.FloatField(default=0)
    Beer = models.FloatField(default=0)
    Cigarette_pack = models.FloatField(default=0)
    Cold_medicince = models.FloatField(default=0)
    Hair_Shampoo = models.FloatField(default=0)
    Toilet_paper = models.FloatField(default=0)
    Toothpaste = models.FloatField(default=0)
    _Gym_Membership = models.FloatField(default=0)
    Cinema_Ticket = models.FloatField(default=0)
    Doctors_visit = models.FloatField(default=0)
    Haircut = models.FloatField(default=0)
    Brand_Jeans = models.FloatField(default=0)
    Brand_Sneakers = models.FloatField(default=0)
    Daycare_or_Preschool = models.FloatField(default=0)
    International_Primary_School = models.FloatField(default=0)
    _Population = models.CharField(default='-')
    State_rank = models.IntegerField(default=0)
    Quality_of_life = models.FloatField(default=0)
    
    def get_absolute_url(self):
        return reverse('cost', args=[self.country_name,self.Name])
    



class Author(models.Model):
    name = models.CharField(max_length=100)
    bio = models.TextField()