# Generated by Django 4.2.4 on 2023-09-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='map',
            field=models.TextField(blank=True, null=True),
        ),
    ]
