# Generated by Django 4.2.4 on 2023-09-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_business_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='text',
            field=models.CharField(default=''),
        ),
    ]
