# Generated by Django 4.2 on 2023-04-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0002_countrytable_total_with_rent_1p'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrytable',
            name='Total_with_rent_3p',
            field=models.FloatField(default=0),
        ),
    ]
