# Generated by Django 4.2 on 2023-04-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0004_countrytable__without_rent_1p_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrytable',
            name='Rent_and_Utilities_1p',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='countrytable',
            name='Rent_and_Utilities_3p',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='countrytable',
            name='Transport_1p',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='countrytable',
            name='Transport_3p',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='countrytable',
            name='_Food_1p',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='countrytable',
            name='_Food_3p',
            field=models.FloatField(default=0),
        ),
    ]
