# Generated by Django 4.2 on 2023-04-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0009_countrytable_daycare_or_preschool_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrytable',
            name='_Population',
            field=models.CharField(default='-'),
        ),
    ]
