# Generated by Django 4.2 on 2023-04-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0010_countrytable__population'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrytable',
            name='country_flag_url',
            field=models.CharField(default='-'),
        ),
        migrations.AddField(
            model_name='countrytable',
            name='country_icon_url',
            field=models.CharField(default='-'),
        ),
    ]
