# Generated by Django 4.2 on 2023-06-25 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0014_citytable_liveability_countrytable_quality_of_life_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
            ],
        ),
    ]
